### ISSUE TITLE
jacksmart can be built, but failed to add to Weave Device Manager app

### ISSUE THREAD

**Issue by tosapon** [googlesamples/brillo-dragonboard-jacksmart#1]
Hi, 
I followed your steps and I could build a Brillo image with jacksmart service on Ubuntu host perfectly (using my own Weave credentials in weaved.conf and my own product ID in config/brillo/product_id). However, in my experiments, this device (jacksmart on Dragonboard 410c) failed to add to the Weave Device Manager app at the final step (finalization). I tested example-ledflasher provided with bdk and it was working well. I'm not sure about this issue. Could you hint something to help me solve or debug this? 
Thank you so much, Todd.

**Comment by gguuss** [comment]
Brillo is no longer supported.
